### ISSUE TITLE
Darstellungsfehler: Fehlende Dynamic im Block bei Auswahl der Felder + Nichtberücksichtigung der Felder

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/rrze-faudir#126]
Wenn ich im Block einzelne Felder auswähle zur Anzeige, werden diese bei einer schon ausgewählten Liste von Personen nicht sofort angepasst.  Auch eine Wechsel des Formats, welches ein Neuladen erbeiführt im Block ändert daran nichts.

Zudem werden Daten nicht angezeigt bzw. die Wahl der Felder scheint nicht zu wirken:

Beispiel:
Anzeige aller Personen der Funktion Leitung (mit im Setting vordefinierter Org 1011120000).
Ich hab gewählt, dass Nachname, E-Mail, Telefon, URL  angezeigt werden. 
Wird aber nicht, sowohl im Format Block, wie Table, wie wird die Wahl zur Anzeige des Nachnamens nicht berücksichtigt.
Wenn ich bsp beim Format Table nur E-Mail, Telefon und Nachname anwähle, bleiben trotzdem die Mail, Telefon und URL sichtbar und es wird nicht der Nachname sondern der Displayxname gezeigt:

<img width="1447" alt="grafik" src="https://github.com/user-attachments/assets/fff687c6-819c-408a-b0a6-a6708a734da5" />

Wenn ich das ganze speichere und veröffentliche, dann jedoch werden nur die EMail und die Telefon-Platzhalter angezeigt, aber mit N/A. Der Nachname fehlt ganz:
<img width="1447" alt="grafik" src="https://github.com/user-attachments/assets/ed50326b-ea8e-4e41-bae6-0c114a35e373" />

Wechsle ich auf Format Liste hab ich ähnliches, nur dass dort im Block die E.Mail und Telefon fehlen und nur Displayname gezeigt wird:
<img width="1447" alt="grafik" src="https://github.com/user-attachments/assets/772041d4-f96b-416c-ba4c-cac1d86390ee" />

Während im Output das dann so aussieht:
<img width="1447" alt="grafik" src="https://github.com/user-attachments/assets/dbccd516-921c-48b7-bd20-ddc092e10081" />

Hinsichtlich der fehlenden Daten mach ich einen eigenen Issue #127

**Comment by FitoreGashi** [comment]
Ahh, die Übersetzung von DisplayName zu Kompletter Name ist nicht korrekt.
Ich habe es so gemacht, dass der Display Name automatisch ausgewählt wird, sobald entweder der Vorname oder der Nachname ausgewählt wird.

Zusätzlich werde ich den Block jedes Mal neu rendern, wenn ein Feld ausgewählt oder abgewählt wird.

**Comment by xwolfde** [comment]
Naja, Displayname ist ja der generierte Name aus den Teilen "akad. Titel + Vorname + Adelstitel + Nachname + Akad. Suffix".

Wenn man in der Feldliste dagegen nur Nachname wählt, soll auch nur Nachname gezeigt werden.
Nur dann wenn man "Displayname" aktiv gewählt hat, dann sollen die Wahl von den Einzelfelder Nachname, Aka,d Titel, Nachname, Adelsname, Akad. Suffix ignoriert werden. Wenn Displayname deaktiv ist, dann nur das anzeigen, was auch aktiviert wurde.

**Comment by xwolfde** [comment]
Ok, Daten kommen aus der API.  Jetzt nur noch das in #127 beschriebene Problem der Datendarstellung...
