### ISSUE TITLE
Abwärtscompatibilität: Übernahme von Shortcode-Funktion von Plugin FAU-Person

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/rrze-faudir#25]
Wenn das Plugin FAU-Person **nicht** aktiv ist, soll dessen Shortcode (als Alias) `[kontakt]` auf den eigenen Shortcode des FAUdir Plugins` [faudir]` angeboten werden.
Somit soll eine rudimentäre Abwärtscompatibilität erreicht werden für Pages und Posts, die den alten Shortcode verwenden um Personen darzustellen.

**Comment by MManthey** [comment]
Bitte nochmal testen, sollte durch #87 auch behoben sein.

**Comment by xwolfde** [comment]
Mit der aktuellen Version von heute früh:

Aktuell werden bei parallelen Betrieb von FAU Person und FAUdir leider noch immer die alten Shortcodes von FAUdir übernommen.
Sowohl bei Nutzung von id als auch mit Category in dem [kontakt] Shortcode

[kontakt id="1130939" format="card"]
[kontakt category="test" format="card"]

aber auch für
[kontaktliste]



Der Fehler liegt in der Erkennung des Plugins FAU-Person in rrze.faudir.php, Zeile 180:

```
   // Check if the FAU-person plugin is not active
    if (!is_plugin_active('fau-person-master/fau-person.php')) { 
        add_shortcode('kontakt', 'kontakt_to_faudir_shortcode_alias');
        add_shortcode('kontaktliste', 'kontaktliste_to_faudir_shortcode_alias');
    }

```

Der Pfad heisst nur dann `fau-person-master`, wenn jemand das ZIP aus GitHub herunterlädt und dann beim installieren den Branchnamen "master" nicht wegmacht ;)

Ihr müsst das auf 
`    if (!is_plugin_active('fau-person/fau-person.php')) { `
ändern.

Und damit ihr nicht von Hand die ZIPs aus dem GitHub holt und dann im falschen Pfad installiert, holt euch doch bitte das Git Updater Plugin von Andy Fragen oder noch besser, nutzt unseren GitHub Updater: https://github.com/RRZE-Webteam/rrze-updater

**Comment by MManthey** [comment]
danke fuer den Hinweis 🙏

**Comment by xwolfde** [comment]
thxs
