### ISSUE TITLE
Generierung Displayname und akademische Titel

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/rrze-faudir#41]
Der Anzeigename einer Person (im Template via {{displayname}})  ergibt sich per Default aus der Form:

`{{displayname}} = {{akademtitel}} {{givenName}} {{familyName}} ({{akademsuffix}})`

(Wenn `{{akademsuffix}}` leer ist, ist auch die runde Klammer wegzulassen)

Der Akademische Titel muss aufgrund der Barrierefreiheit jedoch mit einem `<abbr>` modifiziert und ergänzt werden. 
Über die API erhalten wir den Wert in der Variable `honorificPrefix` in einer der Formen, die unten angegeben sind:

```
'options' => array(
                        '' => __('Keine Angabe', 'fau-person'),
                        'Dr.' => __('Doktor', 'fau-person'),
                        'Prof.' => __('Professor', 'fau-person'),
                        'Prof. Dr.' => __('Professor Doktor', 'fau-person'),
                        'Prof. em.' => __('Professor (Emeritus)', 'fau-person'),
                        'Prof. Dr. em.' => __('Professor Doktor (Emeritus)', 'fau-person'),
                        'PD' => __('Privatdozent', 'fau-person'),
                        'PD Dr.' => __('Privatdozent Doktor', 'fau-person')
                    ),
```
Die generierte AUsgabe und der generierte Wert für  {{akademtitel}}  ist daher zum Beispiel bei einem `honorificPrefix` = "Prof." der Wert: `<abbr title="Professor">Prof.</abbr> `

**Comment by xwolfde** [comment]
Nach Diskussion:

1. Wir erlauben die Übernahme & Anzeige aus der API, wie sie da kommt. (Bei dieser Variante wird es keine abbr für Screenreader geben) . Die Variante aus dem DIP selbst kann ihren Ursprung aus VIVA haben oder auch in FAUdir/IdM manuell durch die Person geändert worden sein.
2. Zusätzlich die Option, eine "hart bereinigte" (nach obigen Vorbild von FAU Person)  Anzeige zu machen.

{{akademtitel}} ist die bereinigte Variante
{{san-akademtitle}} ist die anitizte bereinigte Variante

**Comment by FitoreGashi** [comment]
Um sicherzustellen, dass alle bereinigten Namen in der Ausgabe von FAUdir korrekt behandelt werden, könnten Sie uns bitte eine Liste aller 'hard-sanitized' Namen zur Verfügung stellen, die wir in der aktuellen Implementierung ersetzen müssen?  @xwolfde

**Comment by xwolfde** [comment]
Das sind die in Einstiegsbeitrag ganz oben:
```
'options' => array(
                        '' => __('Keine Angabe', 'fau-person'),
                        'Dr.' => __('Doktor', 'fau-person'),
                        'Prof.' => __('Professor', 'fau-person'),
                        'Prof. Dr.' => __('Professor Doktor', 'fau-person'),
                        'Prof. em.' => __('Professor (Emeritus)', 'fau-person'),
                        'Prof. Dr. em.' => __('Professor Doktor (Emeritus)', 'fau-person'),
                        'PD' => __('Privatdozent', 'fau-person'),
                        'PD Dr.' => __('Privatdozent Doktor', 'fau-person')
                    ), 
```

**Comment by xwolfde** [comment]
Noch zu prüfen mit Personeneinträgen von z.B. Dr. Georg Hager oder Prof. Gergard Wellein.

**Comment by xwolfde** [comment]
Das war gefordert:
`<abbr title="Professor">Prof.</abbr> `


Es wurde aber  so umgesetzt (Test format card)
`<span itemprop="honorificPrefix">Professor Doktor</span> `

<img width="1182" alt="grafik" src="https://github.com/user-attachments/assets/956a9cee-c866-4781-8ed5-42125d2201a3">

Niemals ging es darum, die volle Ausschreibung sichtbar zu machen. Das wurde nicht verlangt. Es ging darum, die Abkürzung nur für Screenreader bereitzustellen.

So wäre es richtig gewesen, wenn man den _itemprop_ noch ergänzt:

`<abbr title="Professor"  itemprop="honorificPrefix">Prof.</abbr>`

**Comment by MManthey** [comment]
sorry, das haben wir missverstanden, sollte jetzt laufen

**Comment by xwolfde** [comment]
Passt!
