### ISSUE TITLE
Ausgabeformat: mehrere Personen als Bildergalerie

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/rrze-faudir#49]
Eine Kontaktübersicht soll als Bildergalerie (Card-Format) ermöglicht werden.
Im Shortcode wird dieses Ausgabeformat mit dem Parameter format="card" angesteuert.
Aufruf wäre im Standardfall eines Shortcodes also:

`[faudir format="card" identifier="" group="" orgnr="" show="" hide=""]`

Von den Parametern
* identifier="" 
* group="" 
* orgnr=""
muss nur mindestens eines angegeben sein. 

Das card-Format steht auch für die Darstellung eines einzelnen Kontaktes zur Verfügung.

Optische Ausgabe in der Form:
<img width="848" alt="grafik" src="https://github.com/RRZE-Webteam/rrze-faudir/assets/1070669/fed36fd6-4c36-4def-b8fb-81d511c4b312">

Die bei dem alten Plugin zusätzliche mögliche Angabe von Personengruppen mit Hilfe der Taxonomie (category="") ist erst nach EInführung eines Custom Post Types ( #33 ) ab der Version 2 nötig. Zu beachten ist, dass das vorherigen Plugin statt `identifier=""` den Parameter ` id="" `nutzte. `Id="" `bezog sich jedoch nicht auf die Identifier der Personen, sondern auf die WordPress-eigene Id des Custom Post Types. Wenn #33 umgesetzt ist, kann erwägt werden, auch diesen Parameter wieder zu berücksichtigen.

Umsetzungshinweis: Bei dem vorherigen Plugin wurde hierzu der Shortcode mit Namen `[kontaktliste]` verwendet.
Wenn das FAU-Person Plugin deaktiviert ist, soll zur Abwärtskompatibilität der Shortcode von FAUdir ebenfalls auf `kontaktliste` hören, sprich dieser Shortcodename ebenfalls registriert werden.

Siehe auch die Dokumentation des vorherige Plugin FAU-Person als Vorlage: 

* Format Card: https://www.wordpress.rrze.fau.de/plugins/neue-inhaltstypen-erstellen/fau-person/format-card/
* Kontaktübersichten: https://www.wordpress.rrze.fau.de/plugins/neue-inhaltstypen-erstellen/fau-person/eine-kontaktuebersicht-erstellen-und-anlegen/
* Alle Formate: https://www.wordpress.rrze.fau.de/plugins/neue-inhaltstypen-erstellen/fau-person/alle-formate-in-der-uebersicht/

**Comment by xwolfde** [comment]
Ist dasselbe. Sind alles Aliase für dieselbe Funktion:
https://github.com/RRZE-Webteam/fau-person/blob/416119a37dda669da933b6c10df27ff1aa50ff78/includes/Shortcodes/Kontakt.php#L30C1-L33C69

**Comment by MManthey** [comment]
sollen wir alle Aliase supporten?

**Comment by xwolfde** [comment]
Ja, es soll ja soweit möglich abwärtscompatibel bleiben. Wenn da eine Zeile reicht, "kostet" das ja nichts.

**Comment by xwolfde** [comment]
Korrektur: Da ist doch was, aber es hat keinen COntent:

<img width="1828" alt="grafik" src="https://github.com/user-attachments/assets/cb20a660-9826-4b67-b9cd-d18601d66af7">

**Comment by xwolfde** [comment]
Okay... Bildformat passt...
