### ISSUE TITLE
Sortieroptionen für Ausgabe mehrerer Kontakte

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/rrze-faudir#57]
Für die Ausgabe von Listen, Tables und Cards für mehrere Personen sind Sortieroptionen vorzusehen.

U.a. können folgende Sortierungsmöglichkeiten sinnvoll sein:

* nach Nachnamen,
* zuerst nach Akadem. Titeln und dann nach Nachnamen
* nach Zugehörigkeit zu Gruppen
* gemäß der Reihenfolge der Identifier, wenn mehrere Pesonen über den Identifier ausgewählt wurden

Zu beachten ist, dass die Sortierung nach Namen ebenfalls Umlaute und Sonderzeichen berücksichten muss, damit Personen mit entsprechenden Sonderzeichen im Namen nicht irgendwo landen.

**Comment by xwolfde** [comment]
Und wie wurde das umgesetzt?

Lt. verlinktem Push gibt es nur die sort-Parameter `title_last_name` und `identifier_order` und Default ist `last_name`. Wie Soertiere ich Personen nach ihren Funktionen/Gruppen? 

Hier braucne wir eine Info/Doku statt nur den Issue zu schliessen.

**Comment by debokshi** [comment]
There are 5 sorting options:
sort="title_last_name" -> it sorts by academic title first 'Prof.Dr.' then 'Dr.' then 'Prof.' then no academic title
sort="last_name" -> it sorts by last name
sort="identifier_order" -> if we are showing specific persons by identifier it will sort by identifier order
sort="function_proffesor" -> it sorts by function professor first then the others
sort="function_head" -> it sorts by function head first then the others

**Comment by xwolfde** [comment]
Ok, but please change the option value
`function_proffesor` to `function_titel`, as in #102
