### ISSUE TITLE
Import Altdaten? Wo?Wie?

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/rrze-faudir#67]
Funktion zum Import der Altdaten funktioniert nicht oder nicht findbar.
#23 scheint nicht zu funktionieren?

**Comment by xwolfde** [comment]
Ok. Damit der automatische Import kjlappt, muss wi efolgt vorgeganegn werden/folgende Bedingungen müssen da sein:

Wenn RRZE Settings noch nicht den Key hatte, dann muss das neue FAUdir bei der Aktivierung trotzdem den Key haben, damit dann was passiert.

Ergo geht es dann so:
1. FAUdir aktivieren
2. Key eingeben
3. FAUdir deaktivieren
4. FAU Person muss aktiv sein
5. FAUdir aktivieren


Dann macht er es.

**Comment by FitoreGashi** [comment]
@debokshi check html esacpe need to display all shortcoed and make a button on setting to initiate a transfer not on activation.

**Comment by xwolfde** [comment]
Weiterer Fehler:
Es wird nicht erkannt, dass ein Personeneintrag aus FAU Person, der zuvor bereits einmal importiert wurde, nicht mehr importiert werden muss. Daher wird dieser wiederholt importiert:

<img width="1297" alt="grafik" src="https://github.com/user-attachments/assets/399b04fd-cfe2-495e-a6f3-4e5b7ac7c669">

Testszenario:
1. FAUdir deaktivieren
2. FAU Person muss aktiv sein
3. FAUdir aktivieren

In #23 wurde diesbzgl hier ein Vorschlag gemacht um da szu verhindern: https://github.com/RRZE-Webteam/rrze-faudir/issues/23#issue-2396039388

**Comment by debokshi** [comment]
@xwolfde Just to clarify you want to have all the custom fields of the old plugin in the new one, right? 
Can you also specify the repeated import, we cannot replicate the error.

**Comment by xwolfde** [comment]
@debokshi 

1. Import from old:
2. 
Which data to import, as written in #24:
- post thumbail / image
- content
- title
- Field "description" -> goes in  teasertext
- Taxonomy-Data of the previous costom post type -> goes to new custom post type  (for filtering the output for more as one entry, as defined in #49   _("Die bei dem alten Plugin zusätzliche mögliche Angabe von Personengruppen mit Hilfe der Taxonomie (category="") ist erst nach EInführung eines Custom Post Types ( https://github.com/RRZE-Webteam/rrze-faudir/issues/33 ) ab der Version 2 nötig. Zu beachten ist, dass das vorherigen Plugin statt identifier="" den Parameter id=""nutzte. Id="" bezog sich jedoch nicht auf die Identifier der Personen, sondern auf die WordPress-eigene Id des Custom Post Types. Wenn https://github.com/RRZE-Webteam/rrze-faudir/issues/33 umgesetzt ist, kann erwägt werden, auch diesen Parameter wieder zu berücksichtigen.")_


All the previous fields for personal data, adress data or social media fields are not used from the old plugin, cause these data fielda are coming from the api (only!) in future. That doenst mean, they wont exists anymore, but they are no longer are editable. All tieses fields are coming from the api.


Example:
<img width="1822" alt="grafik" src="https://github.com/user-attachments/assets/34d87d2d-5503-42ad-94f7-9657b9935a7b">

All other data fields below the fold ("Kontaktinformation" and so on) can be ignored by the import.


2.
To replicate:
I just deactivated the FAUdir plugin.  And activated it again, while FAU person was active and contained those entries **with existing UnivIS Ids** I screenshottet above. If you want to test, create new entrries with FAU Person with the following UnivIS Ids for me 40014582 and for Max: 20891284. After this activate the FAUdir. Then deactivate. Then activate again.

**Comment by MManthey** [comment]
@xwolfde 2 Fragen zur API:

1. Wenn eine Person mehrere Kontakte bei der selben Organisation hat - Ist davon auszugehen, dass **socials** und **workplaces** die selben Werte in den einzelnen Kontakten haben? Oder koennten sich diese auch unterscheiden?
2. Die univis api gibt beispielsweise fuer die Anfrage **http://univis.uni-erlangen.de/prg?search=persons&id=40014582&show=json** die **idm_id: unrz59** zurueck. Wie kann ich jetzt damit den identifier in unserer DIR API bestimmen? Oder ist, nur weil das Feld besetzt ist, nicht davon auszugehen, dass damit was anzufangen ist?

In #23 wurde es ja so beschrieben:
> Sinnvoll ist als erstes das UnivIS-Feld "idm_id" zu verwenden. Dieses sollte die IdM-Kennung enthalten, die man als Query für DIP API nutzen kann.

**Comment by xwolfde** [comment]
Zu 1:

Leider kann es tatsächlich der Fall sein, dass man je Zuordnung in der selben Orga und auch je Sichtbarkeit (Intern oder Öffentlich) unterschiedliche Angaben haben kann.

Hier Screenshots von mir:
Ich bin im RRZE den zwei Gruppen zugeordnet:
- Wissenschaftlich Mitarbeitende
- Leitung

![grafik](https://github.com/user-attachments/assets/7910dcf4-0b13-426a-9b41-88c2856c1a11)

In der Gruppe "Wissenschaftliche Mitarbeitende" hab ich bei meinen "Öffentlichen" Eintrag die folgenden Angaben gemacht:
![grafik](https://github.com/user-attachments/assets/da9bab3e-3f0c-4a3e-b643-c738c7856690)

Also bei Sozialen Medien hab ich da: Xing, GitHub und Bluesky.


In der Gruppe "Leitung" hingegen hab ich als Soziale Meiden nur CRIS angegeben:
![grafik](https://github.com/user-attachments/assets/c346b713-87bb-4d3e-b67a-baeaedae8fcd)

Ausserrdem hab ich da keine Sprechzeiten und Anwesenheitszeiten angegegen.

**Comment by xwolfde** [comment]
Zu 2:
Mit der IdM-Kennung könnt ihr die die API mit dem Endpoint /persons/ und der Suche mit "q". Die Query-Suche erlaubt die Suche nach "uid", welche die Kennung ist:
Also so:
curl -X 'GET' \
```
  'https://api.fau.de/pub/v1/opendir/persons?q=unrz59' \
  -H 'accept: application/json' \
  -H 'X-API-KEY: ....'

```

**Comment by xwolfde** [comment]
passt
