### ISSUE TITLE
Settings: Personen Slug in Lasche Einstellungen verschieben

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/rrze-faudir#85]
Die SLug, auf die man auch bei der Aktivierung hingewiesen wird, befindet sich in der Lasche "Kompaktkarten-Schaltfläche".
Da findet und erwartet man dies nicht.
<img width="1408" alt="grafik" src="https://github.com/user-attachments/assets/81066813-774f-4a05-81b1-a1bdda4b9884">

Bitte lieber unter "API-Einstellungen" verschieben.

**Comment by xwolfde** [comment]
Wurde bereits erfolgreich umgesetzt

**Comment by xwolfde** [comment]
Hm... jetzt ist es in beiden Laschen?

**Comment by MManthey** [comment]
hoppla
