### ISSUE TITLE
Alt-Shortcode führt zu Fehlerausgabe

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/rrze-faudir#87]
Ich hab eine Seite mit den alten Shortcode

`[kontakt id="1129611"]`

Diese Id war die Id eines Beispieleintrags, der nicht importiert wurde (weil er weder UniVIS, noch Idm_kennung hatte)
Nun hab ich das alte Plugin abgeschaltet und es läuft nur noch FAUdir:
<img width="1117" alt="grafik" src="https://github.com/user-attachments/assets/45b4627e-b78f-4b92-982b-57ad3b41f82b">

Nachdem ich FAU Person abschaltete erscheint auf dieser Seite mit obigen Shortcode plötzlich eine Liste (!) verschiedenster Personendaten (aber jeweils ohne Name):

![grafik](https://github.com/user-attachments/assets/f10a2825-ab85-47e8-a664-eff898078bbc)

In den Debug sehe ich, dass hier ein Fetch ohne genauere Filterung gemacht wird und so irgendwelche Leute geholt werden.
`[RRZE-FAUDIR] Fetching persons attributes with URL: https://api.fau.de/pub/v1/opendir/persons?limit=0&offset=0`

Lösung: Wenn hier eine Id angegeben ist, die nicht verknüpft ist mit einem neuen FAUDir-Eintrag (vgl #25 ) und wo somit keine validen und eindeutigen Suchparameter für die API vorliegen, dann bitte hier nur ein Fehler augseben aber nicht auf gut Glück irgendwelche Personen ausgeben ;)
Zumal in diesem Fall bei nur einer id="" es nur ein Ergebnis hätte geben dürfen und nicht viele.

**Comment by xwolfde** [comment]
Sorry, nein, es nicht viel besser. Zwar kommt jetzt nicht mehr umnaufgefordert eine LIste von Leute aus der API, aber dafür ist die Abwärtscompatibiltöt nicht merh vorhanden und überdies ist FAU Person nicht mehr parallel nutzbar( #25 ):


Ich hab das Plugin FAU-Person aktiv. Nun werden aber dessen Shortcodes übernommen von FAUdir.
Es erscheint dann von FAUdir die Meldung  **Person mit ID 1130939 existiert nicht** 

Was eben nicht das gewollte war:
Die Person, die diesen vorherigen Person CPT hatte, wurde auch erfolgreich importiert (mein EIntrag).
Daher hätte der neue FAUdir CFP wissen müssen, dass dieser vorher die alte ID 1130939 hatte.
Und daher dann den Eintrag mit meiner Id anzeigen müssen.
Ref: #23

**Comment by MManthey** [comment]
haben wir gefixt

**Comment by xwolfde** [comment]
passt
