### ISSUE TITLE
Darstellung des Shortcodes Format card

### ISSUE THREAD

**Issue by lukasniebler** [RRZE-Webteam/rrze-faudir#9]
Bei der Darstellung sind die Bilder im Shortcode ab und zu nicht rund, wenn bestimmte Einstellungen / Shortcode-Kombinationen gemacht werden. 

Kundeneinstellungen und Fallbeispiel unter
🎫 http://go.fau.de/9usqd | #4

**Comment by xwolfde** [comment]
Wird komplett neu gemacht. Daher wird der Bug hier erstmal geschlossen, da bei einer Neuimplementierung der Bug hoffentlich nicht mehr vorkommen wird :)
