### ISSUE TITLE
Verwendete Daten zur Ausgabe von Organisation,  "Funktion" und Workplace abhängig machen.

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/rrze-faudir#92]
Je nach Arbeitsplatz und je nach FUnktion kann gewünscht sein, dass unterschiedliche Daten ausgegeben werden.

Daher brauche wir Attribut für die Ausgaben, welches angibt, welche der jeweiligen Datensätze dargestellt werden sollen.

Auserdem sollten wir ein Setting-Wert festlegen und eine Konstante, die im Falle mehrere Datensätze (mehrere Funktionen mit unterschieclichen Daten und/oder mehrere Arbeitsplätze), welcher davon als Default verwendet wird.
Wenn nur  1 Satz vorliegt (nur eine Rolle an einem Arbeitsplatz), dann wird natürlich der verwendet.

**Comment by xwolfde** [comment]
Kopie der Daten von @MManthey aus dem Fall #54 zur Veranschaulichung:


Aus Schema-Person:
```
{
  ...
  "givenName": "Erika",
  "familyName": "Musterfrau",
  ...
  "personalTitle": "Prof. Dr.",
  "personalTitleSuffix": "Ph.D.",
  "titleOfNobility": "van",
  "email": "erika.musterfrau@fau.de",
  "telephone": "+49 9131 85-12345",
  "contacts": [
    {
      ...
      "organization": {
        ...
        "name": "Testorganisationseinheit"
      },
      ...
      "functionLabel": {
        "de": "Wissenschaftliche Mitarbeiter",
        "en": "Scientific staff"
      }
    }
  ]
}
```

Aus Schema-Contact:
```
{
  ...
  "socials": [
    {
      "platform": "github",
      "url": "https://github.com/erikamusterfrau"
    }
  ],
  "workplaces": [
    {
      "room": "01.234",
      "floor": "01",
      "street": "Musterstraße 1",
      "zip": "91058",
      "city": "Erlangen",
      "faumap": "https://karte.fau.de/api/v1/iframe/famos/12345",
      "phones": [
        "+49 9131 85-12345"
      ],
      "fax": "+49 9131 85-1234567",
      "url": "https://www.test.fau.de/person/erika-musterfrau/",
      "mails": [
        "erika.musterfrau@fau.de"
      ],
      "officeHours": [
        {
          "weekday": 1,
          "from": "07:30",
          "to": "16:00"
        }
      ],
      "consultationHours": [
        {
          "weekday": 2,
          "from": "07:30",
          "to": "16:00",
          "comment": "nur über Zoom",
          "url": "https://fau.zoom-x.de/j/1234567890?pwd=fG5xSxQ2dXNu3EMwAWgzSUpBSEFqUT16"
        }
      ],
      ...
    }
  ]
}
```

Aus Schema-Organization:
```
{
  ...
  "address": {
    "phone": "+49 9131 85-12345",
    "mail": "test@fau.de",
    "url": "https://www.test.fau.de",
    "street": "Musterstraße 1",
    "zip": "91054",
    "city": "Erlangen",
    "faumap": "https://karte.fau.de/api/v1/iframe/famos/12345"
  },
  ...
}
```

**Comment by xwolfde** [comment]
In #97 ist die Datenstruktur genauer beschrieben.

Bei der Anzeige einer Person müssen wir also mindstens den Kontext der Organisation vorauswählen. Ggf. über einen Settingswert, in dem man die Id der Organisation eintragen kann.
Da diese Id aber nicht allseits geläufig ist, muss man dazu auch wieder eine Suche machen.

**Comment by xwolfde** [comment]
[faudir orgaid="1011120000" group="Wissenschaftliche Mitarbeiter"]


spreche api an mit der orgaid="1011120000" und hole alle personen die bei der orgaid in genau dieser gruppe sind.

gruppe = 
```
  "functionLabel": {
        "de": "Wissenschaftliche Mitarbeiter",
        "en": "Scientific staff"
      }
```

**Comment by MManthey** [comment]
Filterlogik:
`(category OR function) and (identifier OR id OR orgnr)`

**Comment by xwolfde** [comment]
Hm... ich weiß nicht ob da schon was gemacht wurde. Aber ich sehe da gerade ein Problem.

Wenn ich ein Code hab, wo ich die Category verwende, wird jetzt nichts mehr gezeigt:
<img width="1151" alt="grafik" src="https://github.com/user-attachments/assets/cdbb52fb-dd19-4e58-a9e1-736e85892685" />


Wir müssen wahrscheinlich die Logik nochmal korrigieren.

(category) or (identifier or id) or (function and orgnr) 


Also:
- Wenn der Shortcode/Block eine Ausgabe mit `category=""` will, brauchen wir keine id,identifier oder orgnr, sondern zeigen alle Personeneintrage, die die category haben. **Nur Falls** `category=""` zusammen mit id, identifier oder orgnr verwenden wird, dann verwende hier AND. 
- Wenn` id=""` oder `identifier=""` verwendet wird, dann zeigen wir zunächst die lokalen Daten an, wenn vorhanden. Wenn wir zu einem identifier in dem Moment keine lokalen Daten haben, dann laden wir diese von der API. 
- Wenn function="" gewählt ist, muss im Shortcode entweder identifier oder id oder orgnr angegeben sein, oder die orgnr muss im Backend gesetzt worden sein. Der Aufruf function braucht aber immer einen zusätzliche Angabe.

**Comment by xwolfde** [comment]
Funktioniert leider garnicht, weder im Block noch im Shortcode?

Test mit SHortcodes mit diesen Shortcode-Einträgen:
[faudir orgaid="1011120000" function="Wissenschaftliche Mitarbeiter"]
[faudir function="Wissenschaftliche Mitarbeiter"]
[faudir function="Leiter"]


Überall: Es konnte kein Kontakteintrag gefunden werden.

In den Settings ist als Orga die 1011120000 vorbelegt.


Mit Block auch nichts:

<img width="1723" alt="grafik" src="https://github.com/user-attachments/assets/f7b8ed44-a586-43fd-ae9a-af470097ed15" />

**Comment by FitoreGashi** [comment]
@xwolfde  Ich habe die Tests sowohl auf Englisch als auch auf Deutsch durchgeführt, und es functionitert. Du solltest die Funktion genau so schreiben, wie sie in der API definiert ist. Zum Beispiel: Head oder Leitung, Deputy oder Stellvertretung

Englisch: [faudir function="Head" orgnr="1011120000"]
Deutsch: [faudir function="Leitung"]

**Comment by xwolfde** [comment]
Ah, my mad. Hast recht.

Beim Shortcode geht es mit der richtigen Bezeichnung. Beim Block kriege ich es aber auch mit der richtigen Bezeichnung nicht hin :(


Mein Missverständnis kam daher, dass ich dachte, dass wir auch hier für den Fall, dass wir auf die Setting-Einstellung der Organummer zurückfallen, auch dort variable nach unten gehen, wie hier beschrieben:
https://github.com/RRZE-Webteam/rrze-faudir/issues/99#issuecomment-2531777647 


Sprich, wenn ich nur nach 
[faudir function="Leitung"]
suche und in den Settings 1011120000 eingetragen ist, müsste ich alle Personen finden die in allen unterorgs von 101112 sind. Also z.B. auch 1011126200



Nur dann, wenn im Shortcode die Nummer explizit angegeben ist mit
[faudir function="Leitung" orgnr="1011120000"]
dann soll nicht hierarchisch gesucht werden, sondern exakt diese.

**Comment by FitoreGashi** [comment]
Im Block funktioniert es bei mir, siehe Screenshot. Wir hatten es so verstanden, dass bei der Abfrage nach „Professoren“ die Personen aus der angegebenen Organisation gefunden werden sollen, ohne dass automatisch alle „Children Orgs“ einbezogen werden. Das entspricht auch dem, was im Issue erwähnt wurde.

Ich spreche nochmal mit @MManthey und @debokshi  und prüfe, ob wir das in den gegebenen Zeitrahmen implementieren können. 😊

<img width="1736" alt="Screenshot 2024-12-18 at 15 09 54" src="https://github.com/user-attachments/assets/db184c3b-e48d-4eae-987a-57f59829ab49" />

**Comment by xwolfde** [comment]
Uh, now you got me - I dont know... But the API documentation looks right for it. If this helps and works, do it.

But do you really need it? Wouldnt ist be easier to use lq-Search in /persons/ in the orga-attributs and look if a number starts with the sma eorg nr?

**Comment by xwolfde** [comment]
Ah, du bist Frühaufsteher und hast schon was gemacht. Mir ist noch eingefallen, dass ja Marten (?) bei der Suche nach Personen im Backend mit dem Filter nach der org genau auch schon nach Personen suchte, deren Orgnr mit der Nummernfolge begann.
Ggf. Wäre dieselbe query von dort nutzbar.

Sorry, ist mit erst gerade eingefallen.

Ich bin noch unterwegs und schaue gleich die neue Lösung an.

**Comment by xwolfde** [comment]
Hm, leider:


**Shortcode:**

[faudir orgnr="1011120000" function="Leitung"]

zeigt nun zwar Leute mit der Funktion "Leitung", aber aus völlig anderen Orgnummern, die nicht unterhalb von 101112 sind.
Gewollt war, dass wenn ich diese Nummer eingebe, exakt nur die Personen aus der Orgnr kommen.
Ergebnisse hätte hier nur die Person Marcel Ritter sein dürfen.

<img width="1143" alt="grafik" src="https://github.com/user-attachments/assets/502e06d0-b791-497e-82d6-38dea57dffe7" />


Wenn ich den Shortcode ohne orgnr-Attribut verwende:
[faudir function="Leitung"]

sollte die Orgnr aus der Setting verwendet werden. Diese ist bei mir aktuell auf 1011120000 gestellt:
<img width="1122" alt="grafik" src="https://github.com/user-attachments/assets/a73c55e9-7330-4f9a-9851-217113be772b" />

In diesem Fall, bei Verwendung der Nummer aus der Settings, war ja gewünscht, dass alle Personen der Funktion Leitung gefunden werden, die einer Organisation angehören, die mit 101112 beginnen. DIe Nullen am Ende werden also weggelassen und es wird nicht nur exakt nach nur diese Orga gesucht sondern auch nach denen, die darunter soriert sind.


Leider erhalte ich auch da obige Liste mit Leitungs-Personen aus anderen Einrichtungen, die nicht unterhalb von 101112 sind.

**Block:**

Bei Nutzung der EIngabe erfolgt bei EIngabe von Funktion Leitungund Organisationsnummer 101112000 dasselbe, wie oben beim Shortcode:
<img width="1634" alt="grafik" src="https://github.com/user-attachments/assets/4583bab1-30e9-4c43-948c-ec6533a57da8" />

Wenn ich beim Block keine Nummer eingebe, erscheint nichts, auch wenn ich die Settings im Backend voreingestellt hab.

(Beim Block passiert übrigens erst was, wenn ich ein aktives Element anklicke. Die Eingabe/Änderung der Nummer löst noch nichts aus. Aber das ist erstmal ok.)

**Comment by xwolfde** [comment]
Die Suche nach Funktionen funktiert prinzipiell. Daher nehme ich den Issue hiermit ab.

Allerdings gibt es noch zwei gesonderte Bugs, die dabei sichtbar wurden:
- #126 
- #127
