### ISSUE TITLE
Format Card: Name fehlt, Category-Attribut wirkt nicht richtig

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/rrze-faudir#94]
Es soll der Displayname angezeigt werden. Dieser fehlt aber.
Die URL drumherum wurde gemacht.

<img width="1837" alt="grafik" src="https://github.com/user-attachments/assets/51080160-11d2-4f66-9d24-92976c4c5de7">
Dadurch ist auch die Personenseite nicht aufrufbar, weil man auch das Bild nicht anklicken kann.

Die beiden Personen wurden zuvor importiert.
Die Anzeige erfolgt über
`[faudir format="card" category="test"]`

Ein weiteres problem an dieser Stelle betrifft die Kategorie:

Ich hab eine weitere Person (b51a219844) angelegt. Diese wurde auch im Backend importiert.
Dann hab ich im Backend dann auch dem Post die Kaztegory test zugeordnet.
Trotzdem erscheint diese Person dann nicht bei obiger Anzeige mit category="test".

Sie erscheint nur wenn ich sie über die direkte ID adressiere:
`[faudir format="card" identifier="14216341f6, 3fe2733de0,b51a219844"]`

<img width="896" alt="grafik" src="https://github.com/user-attachments/assets/cb05d733-5399-4cf3-a103-af00014fb671">

Und auch da fehlt der Name.
Und die Reihenfolge der Ids wird nicht berücksichtigt. Der EIntrag von Marcel (Leitung) wäre an dritte Stelle zu führen und nicht an erster, weil die Id als drittes in der identifier="" Angabe steht-

**Comment by debokshi** [comment]
In the settings page you should set the default values, if there are not set then the name values won't appear. Also the default sort is by last name, so [faudir format="card" identifier="14216341f6, 3fe2733de0,b51a219844"] this will sort them by last name, if you want to sort by identifiers you should use the sort option [faudir format="card" identifier="14216341f6,3fe2733de0,b51a219844" sort="identifier_order"]
